# General settings
lang: en
title: Programming Journal
description: >-
  The personal blog of Risan Bagja Pradana. The journal of a passionate coder
  who writes codes for fun. Seriously.
permalink: :title:output_ext
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://risan.io"

# Theme related settings
header_title: risan.io
header_description: A journal of a passionate coder
date_format: "%d %B %Y"
nav_links:
  -
    title: Home
    url: /
  -
    title: About
    url: /about

# Plugin settings
author: Risan Bagja Pradana # Used by feed & seo-tag
twitter: # Used by seo-tag
  username: risanbagja
social: # Used by seo-tag
  name: Risan Bagja Pradana
  links:
    - https://twitter.com/risanbagja
    - https://github.com/risan

# Markdown settings
markdown: kramdown
highlighter: rouge

# Build settings
safe: true
strict_front_matter: true
liquid:
  error_mode: strict
sass:
  style: compressed
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

# Default front matter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      image_thumb: /img/default-featured-thumb.jpg
      image: # Used by seo-tag plugin
        path: /img/default-og.jpg
        width: 1200
        height: 800

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
